# Further information
## Additional commands of interest
The following non exhaustive list provides a few examples of commands and packages that tackle common types of analysis which might be relevant to users of large UK surveys:

- Further regression analysis: the `glm()` command  can be used for fitting a
  large number of regression including Poisson and multinomial models. The
  packages ‘lme4’ and  ‘nlme’  are used to fit respectively linear and non
  linear multilevel models, also known as mixed models.

- Complex survey data and analysis commands and functions can be found in the ‘survey’ package. It includes commands for taking into account stratified and clustered samples, weights compute design effects and confidence intervals, etc.. 

- For users interested in latent variable modelling the
  `factanal()` command from the `stats` package conducts factor analysis. Other resources are available in the `poLCA` (Latent Class
  Analysis), `ltm` (Latent Trait modelling), `sem` (Structural equation
  modelling) packages. The  `Lavaan` package provides functions for structural equation modelling
  including with categorical outcomes.

- Users interested in longitudinal and time series analysis will be interested in the  `stats`and the ‘tseries’ packages. The packages `survival` and `eha` deal with event history and survival analysis, whereas ‘grofit’ and ‘plm’ are designed for panel data and growth analyses.


## Additional online resources
There are hundreds of web sites dedicated to R that users can consult, in addition to CRAN and the main R help list, R-Help with its searchable archives. A few of the most common ones are listed here: 

- [www.ats.ucla.edu/stat/r/](www.ats.ucla.edu/stat/r/) - as with other statistical packages, the UCLA website provides a good starting point for the beginner 

- [www.unt.edu/rss/class/Jon/R_SC/](www.unt.edu/rss/class/Jon/R_SC/) at the University of North Texas provides useful links to R resources 
- [www.r-bloggers.com/](www.r-bloggers.com/) contains many posts about R - in particular,

- [www.r-bloggers.com/r-tutorial-series-r-beginners-guide-and-r-bloggers-updates/](www.r-bloggers.com/r-tutorial-series-r-beginners-guide-and-r-bloggers-updates/)contains useful introductory information 

- [stats.stackexchange.com/](stats.stackexchange.com/) is not specific to R but contains forum-type questions and answers raised by R users 

- [www.harding.edu/fmccown/r/](www.harding.edu/fmccown/r/) presents useful information about graphs in R.

- [www.bristol.ac.uk/cmm/learning/course.html](www.bristol.ac.uk/cmm/learning/course.html) - the Centre for Multilevel modeling at Bristol University has several pages dedicated to R users interested in Multilevel modeling


\newpage

# References
- R Core Team. (2017). R: A language and environment for statistical computing. Vienna, Austria: R Foundation for Statistical Computing. Retrieved from https://www.r-project.org/ RStudio Team. (2016). 
- RStudio: Integrated Development for R. Boston, USA: RStudio, Inc. Retrieved from http://www.rstudio.com/ 
- Tennekes, M. (2017). tmap: Thematic Maps. R package version 1.10. Retrieved from https://cran.r-project.org/package=tmap 
- Wickham, H., & Francois, R. (2016). dplyr: A Grammar of Data Manipulation. R package version 0.5.0. Retrieved from https://cran.r-project.org/package=dplyr 
- Wickham, H. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2009. Retrieved from https://cran.r-project.org/package=ggplot2
