# Further information

### Packages of interest {-}
The following non exhaustive list provides a few examples of commands and packages that tackle common types of analysis which might be relevant to users of large scale social surveys:
  
  - Further regression analysis: the `glm()` command  can be used for fitting a large number of regression models including Poisson and multinomial logistic regression. The
packages `lme4` and   `nlme`  include functions to fit respectively linear and non linear multilevel models, also known as mixed models.

- For users interested in latent variable modelling the `factanal()` command from the `stats` package enables to conducts factor analysis. Other resources are available in the `poLCA` (Latent Class Analysis), `ltm` (Latent Trait modelling), `sem` (Structural Equation Modelling) packages. The  `Lavaan` package also provides a wide range of functions for structural equation modelling including models with  categorical outcomes.

- For those conducting  longitudinal and time series analysis the  `stats`and the ‘tseries’ packages contains useful functions. The packages `survival` and `eha` deal with event history and survival analysis, whereas  `plm` is  designed for panel data and fixed and random effects models.

- Using R for creating maps  is  now common among social scientists and geographers with packages such as `rmaps`, `sp`, `rgdal`,  `rgeos` and `ggmaps`


### Additional online resources {-}
There are hundreds of web sites dedicated to R, in addition to CRAN and the main R help list, R-Help with its searchable archives. A few common ones are listed below: 
  
  - As with other statistical packages, the [UCLA](https://stats.oarc.ucla.edu/r/) and [Princeton University](https://libguides.princeton.edu/data-guides) websites provide a good starting point for beginners
- The [University of North Texas](http://bayes.acs.unt.edu:8083/BayesContent/class/Jon/R_SC/) provides useful links to R resources 
- [The R Bloggers website](https://www.r-bloggers.com) contains many posts about R.
- [Stackexchange](https://stats.stackexchange.com/?tags=r) is not specific to R but contains many forum-type questions and answers raised by R users 
- [This website at Harding University](https://www.harding.edu/fmccown/r/) presents useful information about basic plots in R.
- [This blog](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/) presents detailed tutorials for advanced data visualisation using `ggplot2` 
- [The Centre for Multilevel modeling at Bristol University](https://www.bristol.ac.uk/cmm/learning/online-course/course-topics.html)  has several pages and training courses dedicated to R users interested in Multilevel modelling.
- The UK Data Service has produced training material about creating maps in R, as part of an introduction to [mapping crime data](https://github.com/UKDataServiceOpen/Crime_Data_in_R?tab=readme-ov-file)


\newpage