{
  "hash": "e94e350df445195e0d6693f1d91d251a",
  "result": {
    "markdown": "# Essentials of Data Manipulation\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/setup5_8940232f64548ee09f223c01edfed627'}\n\n:::\n\n\n\nIn this section we will cover  how to recode variables and deal with missing data.\n\n## Creating and transforming numerical variables\nLet's say we would like to transform  our numerical political orientation variable: `leftrigh` into a logarithmic scale. We can use the `log()` function  which is directly available in R Base package and simply  returns the natural logarithm (base-e). We will  use the assignment operator ( <- ) to create a new variable called ‘leftright_log’ from the original variable\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.1_ea4710f6db14ac9b2c4d8d8527fab806'}\n\n```{.r .cell-code}\nbsa$lnleftrigh_log <- log(bsa$leftrigh)\n```\n:::\n\n\n\n\nNote that if we had not specified `bsa$` the command would have created a transformed variable outside of the BSA data frame. We can now check the results with `summary()`\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.2_8add9e5c43880afeac36944ceb305c37'}\n\n```{.r .cell-code}\nsummary(cbind(bsa$lnleftrigh,bsa$leftrigh))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       V1               V2      \n Min.   :0.0000   Min.   :1.00  \n 1st Qu.:0.6931   1st Qu.:2.00  \n Median :0.8755   Median :2.40  \n Mean   :0.8707   Mean   :2.52  \n 3rd Qu.:1.0986   3rd Qu.:3.00  \n Max.   :1.6094   Max.   :5.00  \n NA's   :782      NA's   :782   \n```\n:::\n:::\n\n\n\nPlease note that it is not possible to pass several variables names directly to `summary()`. We need to group them first into a temporary object using `cbind()`. In the output `V1` refers to the first variable, `lnleftrigh`.\n\nWhat if we - hypothetically - wanted to do the same with level of agreement to the statement \"People like me don`t have any say about what the government does\", a categorical variable, originally ranging from  1 (`Agree strongly`) to 5 (`Disagree strongly`)? If we try to repeat what we did before:\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.3_cdaf9ab4d1ebd5e5cfc87f1b816ef541'}\n\n```{.r .cell-code}\nbsa$lngovnosa2 <- log(bsa$govnosa2)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in Math.factor(bsa$govnosa2): 'log' not meaningful for factors\n```\n:::\n:::\n\n\n\n... we get an error, due to the fact that `govnosa2` was imported as a factor, and that `log()` can only be applied to numeric objects.\n\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.4_3b06cb225e4dd957ba0694988de0dac5'}\n\n```{.r .cell-code}\nclass(bsa$govnosa2)       #check to see if it is numeric\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"factor\"\n```\n:::\n\n```{.r .cell-code}\nbsa$govnosa2.n <- as.numeric(bsa$govnosa2)#convert to numeric \nclass(bsa$govnosa2.n)       #check again\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"numeric\"\n```\n:::\n\n```{.r .cell-code}\nbsa$lngovnosa2 <- log(bsa$govnosa2.n) #create new log of the leftright      variable \nsummary(cbind(bsa$lngovnosa2,bsa$govnosa2.n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       V1               V2       \n Min.   :0.0000   Min.   :1.000  \n 1st Qu.:0.6931   1st Qu.:2.000  \n Median :1.0986   Median :3.000  \n Mean   :0.8910   Mean   :2.705  \n 3rd Qu.:1.3863   3rd Qu.:4.000  \n Max.   :1.6094   Max.   :5.000  \n NA's   :2447     NA's   :2447   \n```\n:::\n:::\n\n\n\n\n  We can also create a completely new variable in the dataset. For instance, the following will create  `test` with a constant value of 1.\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.5_17b88dad6a8af0ef90455c2c8b4c8de8'}\n\n```{.r .cell-code}\nbsa$test <- 1\n```\n:::\n\n\n\n\n## Categorical variables\nWe saw in Section 3 that  categorical variables are objects called **factors** in R, with a fixed set of possible  numerical or alphanumerical values (levels) which  can be  accessed with the `levels()` function.\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.6_4c66904465803d20c60b4cea59e8f006'}\n\n```{.r .cell-code}\nlevels(bsa$Married) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Married/living as married\" \"Separated/divorced\"       \n[3] \"Widowed\"                   \"Never married\"            \n```\n:::\n:::\n\n\n\nThe number in the output does not refer to  underlying numerical values to which  labels are added as with other statistical packages, but instead to the position of a given level in the list returned by `level()`.\n\n\n## Recoding variables\n The following commands will create a new variable called `Married2` where respondents  are categorised into two new categories: 'Not partnered' and 'Partnered'. The \"separated/divorced” and “Never married”  categories of the “Married” variable are recoded as  “Not partnered”. It is always advised to create new variables when recoding old ones so the original data is not tampered with.\n \n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.7_b19a37473860ad0c0e20f6d6f7ee0a50'}\n\n```{.r .cell-code}\nbsa$Married2 <- ifelse(bsa$Married==\"Married/living as married\",\"Partnered\",bsa$Married)\nbsa$Married2 <- ifelse(bsa$Married==\"Widowed\" | \n                       bsa$Married==\"Never married\" | \n                      bsa$Married==\"Separated/divorced\",\"Not partnered\",bsa$Married2)\n\ntable(bsa$Married2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nNot partnered     Partnered \n         1778          2209 \n```\n:::\n:::\n\n\n\nThe second and fourth categories have been renamed to ‘Not partnered’. Now we\nhave two levels\n    * Partnered\n    *Not partnered\n\n`ifelse()` is  a convenient tool to use when it is required to work with Base R or when the variables have a limited number of categories. More complex cases may require a more advanced function. The `dplyr` library provides a comprehensive set of data manipulation tools.\n\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.8_e7ec1a28a11fdfbadb8602571294bd5a'}\n\n```{.r .cell-code}\nlibrary(dplyr)\nbsa<-bsa%>%\n     mutate(Married3=case_when(\n               Married == \"Married/living as married\" ~ \"Partnered\",  \n               Married == \"Separated/divorced\" | Married == \"Widowed\" ~ \"Not Partnered\",\n               Married == \"Never married\" ~ \"Not Partnered\"\n)\n)\nbsa$Married3<-as.factor(bsa$Married3)\nsummary(bsa$Married3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNot Partnered     Partnered          NA's \n         1778          2209             1 \n```\n:::\n:::\n\n\n\nWe just created the `Married3` variable, which is identical to `Married2` above, but using the more powerful syntax made available by `dplyr`. Let's decompose it:\n  \n  - `dplyr` use the `pipe` symbol ie `%>%` which enables to sequentially combine functions. We will come back to this later in this guide. \n- `mutate()` is the generic variable creation/alteration command, and can handle complex combinations of conditions as well as multiple simultaneous variable creation operations.\n- `case_when()` is the function that allows recoding numerical, character, or factor variables. On the left hand side of the tilde `~` are the condition or the  values that need to be matched in the original variable , and on the right hand side, the  attributed ie recoded values in the new variable. Note that in this case, the recoded variable is by default a character object and needs to be converted into a factor for easier manipulation. \n\n**Extra tips:**\n  \n  - As with any data manipulation exercise, caution is required, and it is recommended to create new variables with the recoded value rather than alter an original variable when handling missing values.\n- The standard value attribution command in R is `<-`. However, `=` will also work in many cases.\n- Unless explicitly specified (in our case, by adding the bsa$ prefix to variable name), the objects created are not included in the data frame from which they were computed. \n\n## Missing Values\nExplicit missing values in R (ie values that R itself considers as missing) are represented as `NA` for factors and numerical variables. For character variables, missing values are simply empty strings, ie `\"\"`. R has a series of functions specifically designed to handle NAs.\n\nR has fewer safety nets than other packages for handling missing values. Most function won't issue  warn users about whether or how many how many observations with missing values have been dropped. On the other hand, some commands will return error messages and won't run when  missing values are present. This is the case of `mean()` for example.  \n\n### Inspecting missing data\n\nThe logical function `is.na()` assesses each observation in variables and identifies whether  cases are valid or missing. The result will appear as a boolean  TRUE/FALSE vector for each observation. `is.na()` can be  combined  with other functions:\n  \n  - With `table()` in order to get the frequencies of missing values of a specific variable.   \n\n- With sum() in order to count the number of missing observations of variables or whole datasets.  \n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/unnamed-chunk-1_4cf67f95c7f1b5c5258e855124a2907e'}\n\n```{.r .cell-code}\ntable(is.na(bsa$leftrigh))#of missing values in the leftright variable \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n 3206   782 \n```\n:::\n\n```{.r .cell-code}\nsum(is.na(bsa)) # of missing values in the whole dataset\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 41486\n```\n:::\n\n```{.r .cell-code}\nmean(is.na(bsa$leftrigh)) #returns the proportion of NAs...\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1960883\n```\n:::\n\n```{.r .cell-code}\nmean(is.na(bsa)) # returns the proportion in the dataset\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3355712\n```\n:::\n:::\n\n\n\n\n### Recoding missing values as NA (continuous variables)\nIt may sometimes be useful to  recode implicit  missing values (ie  considered by the data producer as missing, but not by R)  of either numeric objects or factors into  `<NA>`,  in order to simplify case selection when conducting analyses.  This can either be done with Base R code or  the more advanced data manipulation functions from the dplyr package that we explored earlier.\n\nLet's assume for a moment  that we would like to get rid of respondents aged under 25 for our analysis. A safe way to proceed is by creating a new variable. \n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.9_1befad8b82ebb41158516a01f6e57816'}\n\n```{.r .cell-code}\nbsa$RAgeCat2 <- bsa$RAgeCat #duplicate variable\ntable(bsa$RAgeCat2)                      \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n18-24 25-34 35-44 45-54 55-59 60-64   65+ \n  223   591   650   729   320   333  1138 \n```\n:::\n\n```{.r .cell-code}\nbsa$RAgeCat2[bsa$RAgeCat2==\"18-24\" ] <- NA #convert responses “18-24”  to NA\ntable(bsa$RAgeCat2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n18-24 25-34 35-44 45-54 55-59 60-64   65+ \n    0   591   650   729   320   333  1138 \n```\n:::\n\n```{.r .cell-code}\ntable(is.na(bsa$RAgeCat2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n 3761   227 \n```\n:::\n:::\n\n\n\nWhy is the number of missing values 227 and not 223 as the original number of respondents aged 18-24? Because there were already 3 missing values for the RAgeCat variable.  \n\nWe can also notice that although there are now no observation left in the 18-24 category, it is still displayed by `table()`. This is because  levels are attributes of factors and are not deleted with observations. We can remove unused levels permanently with `droplevels()`   \n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.10_975d173cfb53d5bcfe104afbd9a22ef8'}\n\n```{.r .cell-code}\nbsa$RAgeCat2<-droplevels(bsa$RAgeCat2)\ntable(bsa$RAgeCat2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n25-34 35-44 45-54 55-59 60-64   65+ \n  591   650   729   320   333  1138 \n```\n:::\n:::\n\n\n\n### Working with missing values\nExplicit missing values (coded as NA) can be taken care of by R’s own missing values functions. For instance using the `na.rm=T` or `na.rm=TRUE` option will remove  missing values from an analysis (typing `?na.rm` will provide more information). Below is a summary of how NAs are dealt with by common R commands:\n\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.11_773ed0e9999d5346a3c7a0e3538e0476'}\n::: {.cell-output-display}\nTable: Treatment of missing values by R commands\n\n|Command                 |Default action                    |Parameter                         |\n|:-----------------------|:---------------------------------|:---------------------------------|\n|*mean(), sd(),median()* |Includes NA (may return an error) |na.rm=T                           |\n|*cor(),cov()*           |Includes NA (may return an error) |*use=\"complete.obs\"*              |\n|*table()*               |Excludes NA                       |*useNA = \"always\"* to display NAs |\n|*xtabs()*               |Excludes NA                       |*addNA = T* to display NAs        |\n|lm(),glm()              |Excludes NA                       |*na.action=NULL*                  |\n:::\n:::\n\n\n\n\n\n## Subsetting datasets\nWhen analysis survey data. it is often necessary to limit the scope of computation to specific groups or subset of the data we may be interested in. There are many ways of subsetting datasets in R. We will review the most common here.  \n\n**Using Base R**\n\nMost subsetting commands involve some form of conditions whereby the characteristics of a subsample of interest are specified. Suppose we would like to examine  the interest for politics among people aged 18-24. \n\nWe can either create an adhoc data frame:\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.12_835c4dc35d0e1bb445f887811acd4bcf'}\n\n```{.r .cell-code}\ntable(bsa$Politics)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n... a great deal,      quite a lot,             some,    not very much, \n              739               982              1179               708 \n or, none at all? \n              379 \n```\n:::\n\n```{.r .cell-code}\nbsa.young<-bsa[bsa$RAgeCat==\"18-24\",]  \ntable(bsa.young$Politics)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n... a great deal,      quite a lot,             some,    not very much, \n               29                41                72                56 \n or, none at all? \n               25 \n```\n:::\n\n```{.r .cell-code}\nbsa.young<-bsa[bsa$RAgeCat==\"18-24\",]\n```\n:::\n\n\n\nOr we can directly limit the extent of the analysis on the go:\n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.13_5a9a4b7d5f8be2b0053538f1b5bfeb29'}\n\n```{.r .cell-code}\n  table(bsa$Politics[bsa$RAgeCat==\"18-24\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n... a great deal,      quite a lot,             some,    not very much, \n               29                41                72                56 \n or, none at all? \n               25 \n```\n:::\n:::\n\n\n\nIn the first example it was necessary to include a comma after specg the condition. This is meant to indicate that we want to retain all variables ie columns in the dataset. The comma is not necessary in the second example as we are already working with a single variable.\n\n**Using dplyr***\n\nNow suppose we want to further restrict the analysis to people  identifying as Males. We could use the same Base R syntax as above, but with more than one condition coding tends to become cumbersome. We could instead use the more convenient syntax from the `dplyr` package. Either: \n\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.14_6f73fb195934702ae5114375910a88f8'}\n\n```{.r .cell-code}\nbsa.young.males<-bsa%>%filter(RAgeCat==\"18-24\" & Rsex==\"Male\")  \ntable(bsa.young.males$Politics)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n... a great deal,      quite a lot,             some,    not very much, \n               15                22                30                18 \n or, none at all? \n                9 \n```\n:::\n:::\n\n\n\n\nOr. as before embed it as a condition within `table()` :\n\n\n\n::: {.cell hash='Manipulation_cache/pdf/4.15_5fb583ffbf8153d35235613a18f7db1c'}\n\n```{.r .cell-code}\n  table(bsa%>%filter(RAgeCat==\"18-24\" & Rsex==\"Male\")%>%select(Politics) )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPolitics\n... a great deal,      quite a lot,             some,    not very much, \n               15                22                30                18 \n or, none at all? \n                9 \n```\n:::\n:::\n\n\n\n\nWe are now equipped with the necessary information to move to the next stage and carry out basic analysis using R.\n\n\\newpage",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}