<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Essentials of Data Manipulation |  Analysing survey data using R</title>
  <meta name="description" content="<br />
Analysing survey data using R</p>" />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Essentials of Data Manipulation |  Analysing survey data using R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Essentials of Data Manipulation |  Analysing survey data using R" />
  
  
  

<meta name="author" content="Pierre Walthéry, Nadia Kennar, Rihab Dahab, UK Data Service" />


<meta name="date" content="2023-09-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="opening-ukds-datasets-in-r.html"/>
<link rel="next" href="descriptive-statistics.html"/>
<script src="libs/jquery/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">UKDS Introduction to R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-r"><i class="fa fa-check"></i><b>1.1</b> What is R ?</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html"><i class="fa fa-check"></i><b>2</b> Using R: essential information</a>
<ul>
<li class="chapter" data-level="2.1" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#download-and-installation"><i class="fa fa-check"></i><b>2.1</b> Download and installation</a></li>
<li class="chapter" data-level="2.2" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#installing-and-setting-up-rstudio"><i class="fa fa-check"></i><b>2.2</b> Installing and setting up RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#interacting-with-r"><i class="fa fa-check"></i><b>2.3</b> Interacting with R</a></li>
<li class="chapter" data-level="2.4" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>2.4</b> Installing and loading packages</a></li>
<li class="chapter" data-level="2.5" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#getting-help"><i class="fa fa-check"></i><b>2.5</b> Getting help</a></li>
<li class="chapter" data-level="2.6" data-path="using-r-essential-information.html"><a href="using-r-essential-information.html#objects"><i class="fa fa-check"></i><b>2.6</b> Objects</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="opening-ukds-datasets-in-r.html"><a href="opening-ukds-datasets-in-r.html"><i class="fa fa-check"></i><b>3</b> Opening UKDS datasets in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="opening-ukds-datasets-in-r.html"><a href="opening-ukds-datasets-in-r.html#essential-information"><i class="fa fa-check"></i><b>3.1</b> Essential information</a></li>
<li class="chapter" data-level="3.2" data-path="opening-ukds-datasets-in-r.html"><a href="opening-ukds-datasets-in-r.html#the-2017-british-social-attitudes-survey"><i class="fa fa-check"></i><b>3.2</b> The 2017 British Social Attitudes Survey</a></li>
<li class="chapter" data-level="3.3" data-path="opening-ukds-datasets-in-r.html"><a href="opening-ukds-datasets-in-r.html#understanding-the-dataset"><i class="fa fa-check"></i><b>3.3</b> Understanding the dataset</a></li>
<li class="chapter" data-level="3.4" data-path="opening-ukds-datasets-in-r.html"><a href="opening-ukds-datasets-in-r.html#identifying-and-selecting-variables"><i class="fa fa-check"></i><b>3.4</b> Identifying and selecting variables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html"><i class="fa fa-check"></i><b>4</b> Essentials of Data Manipulation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#creating-and-transforming-numerical-variables"><i class="fa fa-check"></i><b>4.1</b> Creating and transforming numerical variables</a></li>
<li class="chapter" data-level="4.2" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#categorical-variables"><i class="fa fa-check"></i><b>4.2</b> Categorical variables</a></li>
<li class="chapter" data-level="4.3" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#recoding-variables"><i class="fa fa-check"></i><b>4.3</b> Recoding variables</a></li>
<li class="chapter" data-level="4.4" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#missing-values"><i class="fa fa-check"></i><b>4.4</b> Missing Values</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#inspecting-missing-data"><i class="fa fa-check"></i><b>4.4.1</b> Inspecting missing data</a></li>
<li class="chapter" data-level="4.4.2" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#recoding-missing-values-as-na-continuous-variables"><i class="fa fa-check"></i><b>4.4.2</b> Recoding missing values as NA (continuous variables)</a></li>
<li class="chapter" data-level="4.4.3" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#working-with-missing-values"><i class="fa fa-check"></i><b>4.4.3</b> Working with missing values</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="essentials-of-data-manipulation.html"><a href="essentials-of-data-manipulation.html#subsetting-datasets"><i class="fa fa-check"></i><b>4.5</b> Subsetting datasets</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>5</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="5.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#continuous-variables"><i class="fa fa-check"></i><b>5.1</b> Continuous variables</a></li>
<li class="chapter" data-level="5.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#bivariate-association-between-continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Bivariate association between continuous variables</a></li>
<li class="chapter" data-level="5.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#categorical-variables-1"><i class="fa fa-check"></i><b>5.3</b> Categorical Variables</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#one-way-frequency-tables"><i class="fa fa-check"></i><b>5.3.1</b> One way frequency tables</a></li>
<li class="chapter" data-level="5.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#two-way-or-more-contingency-table"><i class="fa fa-check"></i><b>5.3.2</b> Two way or more contingency table</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#grouped-summary-statistics-for-continuous-variables"><i class="fa fa-check"></i><b>5.4</b> Grouped summary statistics for continuous variables</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="producing-weighted-estimates.html"><a href="producing-weighted-estimates.html"><i class="fa fa-check"></i><b>6</b> Producing weighted estimates</a>
<ul>
<li class="chapter" data-level="6.1" data-path="producing-weighted-estimates.html"><a href="producing-weighted-estimates.html#central-tendency-and-dispersion-continuous-variables"><i class="fa fa-check"></i><b>6.1</b> Central tendency and dispersion (continuous variables)</a></li>
<li class="chapter" data-level="6.2" data-path="producing-weighted-estimates.html"><a href="producing-weighted-estimates.html#frequencies-and-contingency-tables"><i class="fa fa-check"></i><b>6.2</b> Frequencies and contingency tables</a></li>
<li class="chapter" data-level="6.3" data-path="producing-weighted-estimates.html"><a href="producing-weighted-estimates.html#robust-inference"><i class="fa fa-check"></i><b>6.3</b> Robust inference</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="graphs-and-plots.html"><a href="graphs-and-plots.html"><i class="fa fa-check"></i><b>7</b> Graphs and plots</a>
<ul>
<li class="chapter" data-level="7.1" data-path="graphs-and-plots.html"><a href="graphs-and-plots.html#distributional-graphs-for-continuous-variables"><i class="fa fa-check"></i><b>7.1</b> Distributional graphs for continuous variables</a></li>
<li class="chapter" data-level="7.2" data-path="graphs-and-plots.html"><a href="graphs-and-plots.html#plotting-categorical-variables"><i class="fa fa-check"></i><b>7.2</b> Plotting categorical variables</a></li>
<li class="chapter" data-level="7.3" data-path="graphs-and-plots.html"><a href="graphs-and-plots.html#more-advanced-plots"><i class="fa fa-check"></i><b>7.3</b> More advanced plots</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="statistical-testing.html"><a href="statistical-testing.html"><i class="fa fa-check"></i><b>8</b> Statistical testing</a>
<ul>
<li class="chapter" data-level="8.1" data-path="statistical-testing.html"><a href="statistical-testing.html#differences-in-means"><i class="fa fa-check"></i><b>8.1</b> Differences in means</a></li>
<li class="chapter" data-level="8.2" data-path="statistical-testing.html"><a href="statistical-testing.html#differences-in-variance"><i class="fa fa-check"></i><b>8.2</b> Differences in variance</a></li>
<li class="chapter" data-level="8.3" data-path="statistical-testing.html"><a href="statistical-testing.html#significance-of-measures-of-association"><i class="fa fa-check"></i><b>8.3</b> Significance of measures of association</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression-analysis.html"><a href="regression-analysis.html"><i class="fa fa-check"></i><b>9</b> Regression analysis</a></li>
<li class="chapter" data-level="10" data-path="further-information.html"><a href="further-information.html"><i class="fa fa-check"></i><b>10</b> Further information</a>
<ul>
<li class="chapter" data-level="10.1" data-path="further-information.html"><a href="further-information.html#additional-commands-of-interest"><i class="fa fa-check"></i><b>10.1</b> Additional commands of interest</a></li>
<li class="chapter" data-level="10.2" data-path="further-information.html"><a href="further-information.html#additional-online-resources"><i class="fa fa-check"></i><b>10.2</b> Additional online resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>11</b> References</a></li>
<li class="divider"></li>
<li><a href="https://ukdataservice.ac.uk" target="blank">UK Data Service</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><p><img src="pics/UKDS_Logos_Col_Grey_300dpi.png" style="width:6cm" /><br />
Analysing survey data using R</p></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="essentials-of-data-manipulation" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Essentials of Data Manipulation<a href="essentials-of-data-manipulation.html#essentials-of-data-manipulation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this section we will cover how to recode variables and deal with missing data.</p>
<div id="creating-and-transforming-numerical-variables" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Creating and transforming numerical variables<a href="essentials-of-data-manipulation.html#creating-and-transforming-numerical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s say we would like to transform our numerical political orientation variable: <code>leftrigh</code> into a logarithmic scale. We can use the <code>log()</code> function which is directly available in R Base package and simply returns the natural logarithm (base-e). We will use the assignment operator ( &lt;- ) to create a new variable called ‘leftright_log’ from the original variable</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="essentials-of-data-manipulation.html#cb88-1" tabindex="-1"></a>bsa<span class="sc">$</span>lnleftrigh_log <span class="ot">&lt;-</span> <span class="fu">log</span>(bsa<span class="sc">$</span>leftrigh)</span></code></pre></div>
<p>Note that if we had not specified <code>bsa$</code> the command would have created a transformed variable outside of the BSA data frame. We can now check the results with <code>summary()</code></p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="essentials-of-data-manipulation.html#cb89-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">cbind</span>(bsa<span class="sc">$</span>lnleftrigh,bsa<span class="sc">$</span>leftrigh))</span></code></pre></div>
<pre><code>##        V1            V2     
##  Min.   :0.0   Min.   :1.0  
##  1st Qu.:0.7   1st Qu.:2.0  
##  Median :0.9   Median :2.4  
##  Mean   :0.9   Mean   :2.5  
##  3rd Qu.:1.1   3rd Qu.:3.0  
##  Max.   :1.6   Max.   :5.0  
##  NA&#39;s   :782   NA&#39;s   :782</code></pre>
<p>Please note that it is not possible to pass several variables names directly to <code>summary()</code>. We need to group them first into a temporary object using <code>cbind()</code>. In the output <code>V1</code> refers to the first variable, <code>lnleftrigh</code>.</p>
<p>What if we - hypothetically - wanted to do the same with level of agreement to the statement “People like me don<code>t have any say about what the government does", a categorical variable, originally ranging from  1 (</code>Agree strongly<code>) to 5 (</code>Disagree strongly`)? If we try to repeat what we did before:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="essentials-of-data-manipulation.html#cb91-1" tabindex="-1"></a>bsa<span class="sc">$</span>lngovnosa2 <span class="ot">&lt;-</span> <span class="fu">log</span>(bsa<span class="sc">$</span>govnosa2)</span></code></pre></div>
<pre><code>## Error in Math.factor(bsa$govnosa2): &#39;log&#39; not meaningful for factors</code></pre>
<p>… we get an error, due to the fact that <code>govnosa2</code> was imported as a factor, and that <code>log()</code> can only be applied to numeric objects.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="essentials-of-data-manipulation.html#cb93-1" tabindex="-1"></a><span class="fu">class</span>(bsa<span class="sc">$</span>govnosa2)                       <span class="co">#check to see if it is numeric</span></span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="essentials-of-data-manipulation.html#cb95-1" tabindex="-1"></a>bsa<span class="sc">$</span>govnosa2.n <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(bsa<span class="sc">$</span>govnosa2)  <span class="co">#convert to numeric </span></span>
<span id="cb95-2"><a href="essentials-of-data-manipulation.html#cb95-2" tabindex="-1"></a><span class="fu">class</span>(bsa<span class="sc">$</span>govnosa2.n)                       <span class="co">#check again</span></span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="essentials-of-data-manipulation.html#cb97-1" tabindex="-1"></a>bsa<span class="sc">$</span>lngovnosa2 <span class="ot">&lt;-</span> <span class="fu">log</span>(bsa<span class="sc">$</span>govnosa2.n) <span class="co">#create new log of the leftright      variable </span></span>
<span id="cb97-2"><a href="essentials-of-data-manipulation.html#cb97-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">cbind</span>(bsa<span class="sc">$</span>lngovnosa2,bsa<span class="sc">$</span>govnosa2.n))</span></code></pre></div>
<pre><code>##        V1             V2      
##  Min.   :0.0    Min.   :1.0   
##  1st Qu.:0.7    1st Qu.:2.0   
##  Median :1.1    Median :3.0   
##  Mean   :0.9    Mean   :2.7   
##  3rd Qu.:1.4    3rd Qu.:4.0   
##  Max.   :1.6    Max.   :5.0   
##  NA&#39;s   :2447   NA&#39;s   :2447</code></pre>
<p>We can also create a completely new variable in the dataset. For instance, the following will create <code>test</code> with a constant value of 1.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="essentials-of-data-manipulation.html#cb99-1" tabindex="-1"></a>bsa<span class="sc">$</span>test <span class="ot">&lt;-</span> <span class="dv">1</span></span></code></pre></div>
</div>
<div id="categorical-variables" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Categorical variables<a href="essentials-of-data-manipulation.html#categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We saw in Section 3 that categorical variables are objects called <strong>factors</strong> in R, with a fixed set of possible numerical or alphanumerical values (levels) which can be accessed with the <code>levels()</code> function.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="essentials-of-data-manipulation.html#cb100-1" tabindex="-1"></a><span class="fu">levels</span>(bsa<span class="sc">$</span>Married) </span></code></pre></div>
<pre><code>## [1] &quot;Married/living as married&quot;
## [2] &quot;Separated/divorced&quot;       
## [3] &quot;Widowed&quot;                  
## [4] &quot;Never married&quot;</code></pre>
<p>The number in the output does not refer to underlying numerical values to which labels are added as with other statistical packages, but instead to the position of a given level in the list returned by <code>level()</code>.</p>
</div>
<div id="recoding-variables" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Recoding variables<a href="essentials-of-data-manipulation.html#recoding-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The following commands will create a new variable called <code>Married2</code> where respondents are categorised into two new categories: ‘Not partnered’ and ‘Partnered’. The “separated/divorced” and “Never married” categories of the “Married” variable are recoded as “Not partnered”. It is always advised to create new variables when recoding old ones so the original data is not tampered with.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="essentials-of-data-manipulation.html#cb102-1" tabindex="-1"></a>bsa<span class="sc">$</span>Married2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(bsa<span class="sc">$</span>Married<span class="sc">==</span><span class="st">&quot;Married/living as married&quot;</span>,<span class="st">&quot;Partnered&quot;</span>,bsa<span class="sc">$</span>Married)</span>
<span id="cb102-2"><a href="essentials-of-data-manipulation.html#cb102-2" tabindex="-1"></a>bsa<span class="sc">$</span>Married2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(bsa<span class="sc">$</span>Married<span class="sc">==</span><span class="st">&quot;Widowed&quot;</span> <span class="sc">|</span> </span>
<span id="cb102-3"><a href="essentials-of-data-manipulation.html#cb102-3" tabindex="-1"></a>                       bsa<span class="sc">$</span>Married<span class="sc">==</span><span class="st">&quot;Never married&quot;</span> <span class="sc">|</span> </span>
<span id="cb102-4"><a href="essentials-of-data-manipulation.html#cb102-4" tabindex="-1"></a>                      bsa<span class="sc">$</span>Married<span class="sc">==</span><span class="st">&quot;Separated/divorced&quot;</span>,<span class="st">&quot;Not partnered&quot;</span>,bsa<span class="sc">$</span>Married2)</span>
<span id="cb102-5"><a href="essentials-of-data-manipulation.html#cb102-5" tabindex="-1"></a></span>
<span id="cb102-6"><a href="essentials-of-data-manipulation.html#cb102-6" tabindex="-1"></a><span class="fu">table</span>(bsa<span class="sc">$</span>Married2)</span></code></pre></div>
<pre><code>## 
## Not partnered     Partnered 
##          1778          2209</code></pre>
<p>The second and fourth categories have been renamed to ‘Not partnered’. Now we
have two levels
* Partnered
*Not partnered</p>
<p><code>ifelse()</code> is a convenient tool to use when it is required to work with Base R or when the variables have a limited number of categories. More complex cases may require a more advanced function. The <code>dplyr</code> library provides a comprehensive set of data manipulation tools.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="essentials-of-data-manipulation.html#cb104-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb104-2"><a href="essentials-of-data-manipulation.html#cb104-2" tabindex="-1"></a>bsa<span class="ot">&lt;-</span>bsa<span class="sc">%&gt;%</span><span class="fu">mutate</span>(<span class="at">Married3=</span><span class="fu">case_when</span>(</span>
<span id="cb104-3"><a href="essentials-of-data-manipulation.html#cb104-3" tabindex="-1"></a>                    Married <span class="sc">==</span> <span class="st">&quot;Married/living as married&quot;</span> <span class="sc">~</span> <span class="st">&quot;Partnered&quot;</span>,  </span>
<span id="cb104-4"><a href="essentials-of-data-manipulation.html#cb104-4" tabindex="-1"></a>                    Married <span class="sc">==</span> <span class="st">&quot;Separated/divorced&quot;</span> <span class="sc">|</span> Married <span class="sc">==</span> <span class="st">&quot;Widowed&quot;</span> <span class="sc">~</span> <span class="st">&quot;Not Partnered&quot;</span>,</span>
<span id="cb104-5"><a href="essentials-of-data-manipulation.html#cb104-5" tabindex="-1"></a>                    Married <span class="sc">==</span> <span class="st">&quot;Never married&quot;</span> <span class="sc">~</span> <span class="st">&quot;Not Partnered&quot;</span></span>
<span id="cb104-6"><a href="essentials-of-data-manipulation.html#cb104-6" tabindex="-1"></a>)</span>
<span id="cb104-7"><a href="essentials-of-data-manipulation.html#cb104-7" tabindex="-1"></a>)</span>
<span id="cb104-8"><a href="essentials-of-data-manipulation.html#cb104-8" tabindex="-1"></a>bsa<span class="sc">$</span>Married3<span class="ot">&lt;-</span><span class="fu">as.factor</span>(bsa<span class="sc">$</span>Married3)</span>
<span id="cb104-9"><a href="essentials-of-data-manipulation.html#cb104-9" tabindex="-1"></a><span class="fu">summary</span>(bsa<span class="sc">$</span>Married3)</span></code></pre></div>
<pre><code>## Not Partnered     Partnered          NA&#39;s 
##          1778          2209             1</code></pre>
<p>We just created the <code>Married3</code> variable, which is identical to <code>Married2</code> above, but using the more powerful syntax made available by <code>dplyr</code>. Let’s decompose it:</p>
<ul>
<li><code>dplyr</code> use the <code>pipe</code> symbol ie <code>%&gt;%</code> which enables to sequentially combine functions. We will come back to this later in this guide.</li>
<li><code>mutate()</code> is the generic variable creation/alteration command, and can handle complex combinations of conditions as well as multiple simultaneous variable creation operations.</li>
<li><code>case_when()</code> is the function that allows recoding numerical, character, or factor variables. On the left hand side of the tilde <code>~</code> are the condition or the values that need to be matched in the original variable , and on the right hand side, the attributed ie recoded values in the new variable. Note that in this case, the recoded variable is by default a character object and needs to be converted into a factor for easier manipulation.</li>
</ul>
<p><strong>Extra tips:</strong></p>
<ul>
<li>As with any data manipulation exercise, caution is required, and it is recommended to create new variables with the recoded value rather than alter an original variable when handling missing values.</li>
<li>The standard value attribution command in R is <code>&lt;-</code>. However, <code>=</code> will also work in many cases.</li>
<li>Unless explicitly specified (in our case, by adding the bsa$ prefix to variable name), the objects created are not included in the data frame from which they were computed.</li>
</ul>
</div>
<div id="missing-values" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Missing Values<a href="essentials-of-data-manipulation.html#missing-values" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Explicit missing values in R (ie values that R itself considers as missing) are represented as <code>NA</code> for factors and numerical variables. For character variables, missing values are simply empty strings, ie <code>""</code>. R has a series of functions specifically designed to handle NAs.</p>
<p>R has fewer safety nets than other packages for handling missing values. Most function won’t issue warn users about whether or how many how many observations with missing values have been dropped. On the other hand, some commands will return error messages and won’t run when missing values are present. This is the case of <code>mean()</code> for example.</p>
<div id="inspecting-missing-data" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Inspecting missing data<a href="essentials-of-data-manipulation.html#inspecting-missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The logical function <code>is.na()</code> assesses each observation in variables and identifies whether cases are valid or missing. The result will appear as a boolean TRUE/FALSE vector for each observation. <code>is.na()</code> can be combined with other functions:</p>
<ul>
<li><p>With <code>table()</code> in order to get the frequencies of missing values of a specific variable.</p></li>
<li><p>With sum() in order to count the number of missing observations of variables or whole datasets.</p></li>
</ul>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="essentials-of-data-manipulation.html#cb106-1" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">is.na</span>(bsa<span class="sc">$</span>leftrigh))  <span class="co">#of missing values in the leftright variable </span></span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  3206   782</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="essentials-of-data-manipulation.html#cb108-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(bsa))           <span class="co"># of missing values in the whole dataset</span></span></code></pre></div>
<pre><code>## [1] 41486</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="essentials-of-data-manipulation.html#cb110-1" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">is.na</span>(bsa<span class="sc">$</span>leftrigh)) <span class="co">#returns the proportion of NAs...</span></span></code></pre></div>
<pre><code>## [1] 0.1961</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="essentials-of-data-manipulation.html#cb112-1" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">is.na</span>(bsa)) <span class="co"># returns the proportion in the dataset</span></span></code></pre></div>
<pre><code>## [1] 0.3356</code></pre>
</div>
<div id="recoding-missing-values-as-na-continuous-variables" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> Recoding missing values as NA (continuous variables)<a href="essentials-of-data-manipulation.html#recoding-missing-values-as-na-continuous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It may sometimes be useful to recode implicit missing values (ie considered by the data producer as missing, but not by R) of either numeric objects or factors into <code>&lt;NA&gt;</code>, in order to simplify case selection when conducting analyses. This can either be done with Base R code or the more advanced data manipulation functions from the dplyr package that we explored earlier.</p>
<p>Let’s assume for a moment that we would like to get rid of respondents aged under 25 for our analysis. A safe way to proceed is by creating a new variable.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="essentials-of-data-manipulation.html#cb114-1" tabindex="-1"></a>bsa<span class="sc">$</span>RAgeCat2 <span class="ot">&lt;-</span> bsa<span class="sc">$</span>RAgeCat           <span class="co">#duplicate variable</span></span>
<span id="cb114-2"><a href="essentials-of-data-manipulation.html#cb114-2" tabindex="-1"></a><span class="fu">table</span>(bsa<span class="sc">$</span>RAgeCat2)                      </span></code></pre></div>
<pre><code>## 
## 18-24 25-34 35-44 45-54 55-59 60-64   65+ 
##   223   591   650   729   320   333  1138</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="essentials-of-data-manipulation.html#cb116-1" tabindex="-1"></a>bsa<span class="sc">$</span>RAgeCat2[bsa<span class="sc">$</span>RAgeCat2<span class="sc">==</span><span class="st">&quot;18-24&quot;</span> ] <span class="ot">&lt;-</span> <span class="cn">NA</span>   <span class="co">#convert responses “18-24”  to NA</span></span>
<span id="cb116-2"><a href="essentials-of-data-manipulation.html#cb116-2" tabindex="-1"></a><span class="fu">table</span>(bsa<span class="sc">$</span>RAgeCat2)</span></code></pre></div>
<pre><code>## 
## 18-24 25-34 35-44 45-54 55-59 60-64   65+ 
##     0   591   650   729   320   333  1138</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="essentials-of-data-manipulation.html#cb118-1" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">is.na</span>(bsa<span class="sc">$</span>RAgeCat2))</span></code></pre></div>
<pre><code>## 
## FALSE  TRUE 
##  3761   227</code></pre>
<p>Why is the number of missing values 227 and not 223 as the original number of respondents aged 18-24? Because there were already 3 missing values for the RAgeCat variable.</p>
<p>We can also notice that although there are now no observation left in the 18-24 category, it is still displayed by <code>table()</code>. This is because levels are attributes of factors and are not deleted with observations. We can remove unused levels permanently with <code>droplevels()</code></p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="essentials-of-data-manipulation.html#cb120-1" tabindex="-1"></a>bsa<span class="sc">$</span>RAgeCat2<span class="ot">&lt;-</span><span class="fu">droplevels</span>(bsa<span class="sc">$</span>RAgeCat2)</span>
<span id="cb120-2"><a href="essentials-of-data-manipulation.html#cb120-2" tabindex="-1"></a><span class="fu">table</span>(bsa<span class="sc">$</span>RAgeCat2)</span></code></pre></div>
<pre><code>## 
## 25-34 35-44 45-54 55-59 60-64   65+ 
##   591   650   729   320   333  1138</code></pre>
</div>
<div id="working-with-missing-values" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Working with missing values<a href="essentials-of-data-manipulation.html#working-with-missing-values" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Explicit missing values (coded as NA) can be taken care of by R’s own missing values functions. For instance using the <code>na.rm=T</code> or <code>na.rm=TRUE</code> option will remove missing values from an analysis (typing <code>?na.rm</code> will provide more information). Below is a summary of how NAs are dealt with by common R commands:</p>
<table style="width:100%;">
<caption>(#tab:4.11)Treatment of missing values by R commands</caption>
<colgroup>
<col width="26%" />
<col width="36%" />
<col width="36%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Command</th>
<th align="left">Default action</th>
<th align="left">Parameter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><em>mean(), sd(),median()</em></td>
<td align="left">Includes NA (may return an error)</td>
<td align="left">na.rm=T</td>
</tr>
<tr class="even">
<td align="left"><em>cor(),cov()</em></td>
<td align="left">Includes NA (may return an error)</td>
<td align="left"><em>use=“complete.obs”</em></td>
</tr>
<tr class="odd">
<td align="left"><em>table()</em></td>
<td align="left">Excludes NA</td>
<td align="left"><em>useNA = “always”</em> to display NAs</td>
</tr>
<tr class="even">
<td align="left"><em>xtabs()</em></td>
<td align="left">Excludes NA</td>
<td align="left"><em>addNA = T</em> to display NAs</td>
</tr>
<tr class="odd">
<td align="left">lm(),glm()</td>
<td align="left">Excludes NA</td>
<td align="left"><em>na.action=NULL</em></td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="subsetting-datasets" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Subsetting datasets<a href="essentials-of-data-manipulation.html#subsetting-datasets" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When analysis survey data. it is often necessary to limit the scope of computation to specific groups or subset of the data we may be interested in. There are many ways of subsetting datasets in R. We will review the most common here.</p>
<p><strong>Using Base R</strong></p>
<p>Most subsetting commands involve some form of conditions whereby the characteristics of a subsample of interest are specified. Suppose we would like to examine the interest for politics among people aged 18-24.</p>
<p>We can either create an adhoc data frame:</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="essentials-of-data-manipulation.html#cb122-1" tabindex="-1"></a><span class="fu">table</span>(bsa<span class="sc">$</span>Politics)</span></code></pre></div>
<pre><code>## 
## ... a great deal,      quite a lot,             some, 
##               739               982              1179 
##    not very much,  or, none at all? 
##               708               379</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="essentials-of-data-manipulation.html#cb124-1" tabindex="-1"></a>bsa.young<span class="ot">&lt;-</span>bsa[bsa<span class="sc">$</span>RAgeCat<span class="sc">==</span><span class="st">&quot;18-24&quot;</span>,]  </span>
<span id="cb124-2"><a href="essentials-of-data-manipulation.html#cb124-2" tabindex="-1"></a><span class="fu">table</span>(bsa.young<span class="sc">$</span>Politics)</span></code></pre></div>
<pre><code>## 
## ... a great deal,      quite a lot,             some, 
##                29                41                72 
##    not very much,  or, none at all? 
##                56                25</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="essentials-of-data-manipulation.html#cb126-1" tabindex="-1"></a>bsa.young<span class="ot">&lt;-</span>bsa[bsa<span class="sc">$</span>RAgeCat<span class="sc">==</span><span class="st">&quot;18-24&quot;</span>,]</span></code></pre></div>
<p>Or we can directly limit the extent of the analysis on the go:</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="essentials-of-data-manipulation.html#cb127-1" tabindex="-1"></a>  <span class="fu">table</span>(bsa<span class="sc">$</span>Politics[bsa<span class="sc">$</span>RAgeCat<span class="sc">==</span><span class="st">&quot;18-24&quot;</span>])</span></code></pre></div>
<pre><code>## 
## ... a great deal,      quite a lot,             some, 
##                29                41                72 
##    not very much,  or, none at all? 
##                56                25</code></pre>
<p>In the first example it was necessary to include a comma after specg the condition. This is meant to indicate that we want to retain all variables ie columns in the dataset. The comma is not necessary in the second example as we are already working with a single variable.</p>
<p><strong>Using dplyr</strong>*</p>
<p>Now suppose we want to further restrict the analysis to people identifying as Males. We could use the same Base R syntax as above, but with more than one condition coding tends to become cumbersome. We could instead use the more convenient syntax from the <code>dplyr</code> package. Either:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="essentials-of-data-manipulation.html#cb129-1" tabindex="-1"></a>bsa.young.males<span class="ot">&lt;-</span>bsa<span class="sc">%&gt;%</span><span class="fu">filter</span>(RAgeCat<span class="sc">==</span><span class="st">&quot;18-24&quot;</span> <span class="sc">&amp;</span> Rsex<span class="sc">==</span><span class="st">&quot;Male&quot;</span>)  </span>
<span id="cb129-2"><a href="essentials-of-data-manipulation.html#cb129-2" tabindex="-1"></a><span class="fu">table</span>(bsa.young.males<span class="sc">$</span>Politics)</span></code></pre></div>
<pre><code>## 
## ... a great deal,      quite a lot,             some, 
##                15                22                30 
##    not very much,  or, none at all? 
##                18                 9</code></pre>
<p>Or. as before embed it as a condition within <code>table()</code> :</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="essentials-of-data-manipulation.html#cb131-1" tabindex="-1"></a>  <span class="fu">table</span>(bsa<span class="sc">%&gt;%</span><span class="fu">filter</span>(RAgeCat<span class="sc">==</span><span class="st">&quot;18-24&quot;</span> <span class="sc">&amp;</span> Rsex<span class="sc">==</span><span class="st">&quot;Male&quot;</span>)<span class="sc">%&gt;%</span><span class="fu">select</span>(Politics) )</span></code></pre></div>
<pre><code>## Politics
## ... a great deal,      quite a lot,             some, 
##                15                22                30 
##    not very much,  or, none at all? 
##                18                 9</code></pre>
<p>We are now equipped with the necessary information to move to the next stage and carry out basic analysis using R.</p>
<div style="page-break-after: always;"></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="opening-ukds-datasets-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="descriptive-statistics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
